CREATE TABLE Book
(
BookID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
ISBN TEXT(13) NOT NULL UNIQUE,
Title TEXT DEFAULT '' NOT NULL,
Edition TEXT DEFAULT '',
Author TEXT,
PublicationDate INTEGER,
Cost DECIMAL(8,2)
);