CREATE TABLE Book
(
BookID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
ISBN TEXT(13) NOT NULL UNIQUE,
Title TEXT DEFAULT '' NOT NULL,
Edition TEXT DEFAULT '',
Author TEXT,
PublicationDate INTEGER,
Cost DECIMAL(8,2)
);



CREATE TABLE BookCopy
(
BookCopyID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
SKU TEXT NOT NULL UNIQUE,
BookID_Book INTEGER NOT NULL REFERENCES Book (BookID)
);



CREATE TABLE Borrower
(
LibraryCardID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
Name TEXT,
Address TEXT,
PostalCode TEXT,
PhoneNumber TEXT(10),
MembershipDate INTEGER
);



CREATE TABLE Librarian
(
LibrarianID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
Name TEXT,
PhoneNumber TEXT(10)
);



CREATE TABLE CheckoutLedger
(
LibrarianID_Librarian INTEGER NOT NULL REFERENCES Librarian (LibrarianID),
CheckoutDate INTEGER NOT NULL,
DueDate INTEGER NOT NULL,
LibraryCardID_Borrower INTEGER NOT NULL REFERENCES Borrower (LibraryCardID),
BookCopyID_BookCopy INTEGER NOT NULL UNIQUE REFERENCES BookCopy (BookCopyID)
);
